apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: nuhman9260/hotel-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: DATABASE_URL
          value: postgres://microservice_project:Nuhman@456@hotel-db:5432/hotel_db
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
