apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: payment-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: microservice-project
        - name: POSTGRES_PASSWORD
          value: Nuhman@456
        - name: POSTGRES_DB
          value: payment_db
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
spec:
  selector:
    app: payment-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
